---
# tasks file for emorylib_redis-dump_to_s3
- name:
  debug:
    msg: '{{ ansible_env.HOME }}'

- debug:
    msg: 'Conditional is working'
  when: redis_dump.dest | dirname == ""
  
- pause:

- name: Include tasks to install redis-dump via gem
  include_tasks:
    file: gem-install-redis-dump.yml

- name: Include tasks to run redis-dump of database
  include_tasks:
    file: redis-dump.yml

- name: Include tasks to upload file to s3 bucket
  include_tasks:
    file: upload-to-s3.yml
  when: redis_dump.s3 is defined
