---
- name: Upload file to s3 bucket
  s3_sync:
    bucket: '{{ redis_dump.s3.bucket }}'
    file_root: '{{ redis_dump.dest | dirname | d ("~/") }}'
    region: '{{ redis_dump.s3.region }}'
    key_prefix: '{{ redis_dump.s3.key_prefix }}'
    include: '{{ redis_dump.dest | basename }}'