---
- name: Upload file to s3 bucket
  s3_sync:
    bucket: '{{ redis_dump.s3.bucket }}'
    file_root: '{{ file_root_ternary }}'
    region: '{{ redis_dump.s3.region }}'
    key_prefix: '{{ redis_dump.s3.key_prefix }}'
    include: '{{ redis_dump.dest  | basename }}.json'
  vars:
    file_root_ternary: '{{ (redis_dump.dest | dirname == "") | ternary (home_dir, dir_name) }}'
    home_dir: '{{ ansible_env.HOME }}'
    dir_name: '{{ redis_dump.dest | dirname }}'